default_cam_config = {
    "EM_MODE": 1,
    "EM_GAIN": 2,
    "FRAME_TRANSFER": False,
    "READOUT_RATE": 0,
    "PREAMP": 0,
    "READ_MODE": 4,
    "ACQUISITION_MODE": 3,
    "TRIGGER_MODE": 0,
    "VERTICAL_CLOCK_VOLTAGE": 0,
    "VERTICAL_SHIFT_SPEED": 3,
    "SHUTTER_MODE": 2,
    "SHUTTER_TTL": 0,
    "SHUTTER_OPENING_TIME": 50,
    "SHUTTER_CLOSING_TIME": 50,
    "INITIAL_COLUMN": 1,
    "INITIAL_LINE": 1,
    "FINAL_COLUMN": 1024,
    "FINAL_LINE": 1024,
    "VBIN": 1,
    "HBIN": 1,
    "AD_CHANNEL": 0,
}
default_acq_config = {
    "EXPTIME": 2,
    "#FRAMES": 1,
    "#CYCLES": 1,
    "suffix": "",
    "COOLER_POWER_STATUS": 1,
    "TEMP": 20,
    "WAVEPLATE_POS": 1,
}
